import{a as P,S as M,i}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function y(o,t){return(await P("https://pixabay.com/api/",{params:{key:"52541066-61f39c635ccb9e2a2a197a680",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}})).data}let d;const g=document.querySelector(".loader"),p=document.querySelector(".button"),O=document.querySelector("input"),L=document.querySelector(".gallery");function A(){O.value=""}function b(o){const t=o.map(({webformatURL:s,largeImageURL:l,tags:e,likes:r,views:c,comments:$,downloads:v})=>`<li class="gallery-item">
  <a class="gallery-link" href="${l}">
    <img
      class="gallery-image"
      src="${s}"
      alt="${e}"
    />
  </a>
  <ul class = "discription">
  <li class = "item"><h2 class = "title">Likes</h2>${r}</li>
  <li class = "item"><h2 class = "title">Views</h2>${c}</li>
  <li class = "item"><h2 class = "title">Comments</h2>${$}</li>
  <li class = "item"><h2 class = "title">Downloads</h2>${v}</li>
  </ul>
</li>`).join("");L.insertAdjacentHTML("beforeend",t),d?d.refresh():(d=new M(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,captionPosition:"bottom"}),d.on("show.simplelightbox",function(s){console.log(`Open: ${s.target.querySelector("img").alt}`)}))}function h(){L.innerHTML=""}function w(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}function S(){p.classList.remove("hidden")}function a(){p.classList.add("hidden")}const I=document.querySelector(".form"),_=document.querySelector(".button");I.addEventListener("submit",x);let m,n=1,f=0,q=15;async function x(o){if(o.preventDefault(),n=1,w(),m=o.target.elements["search-text"].value.toLowerCase().trim(),m===""){u(),a(),i.warning({message:"Please fill in all required fields"});return}h();try{const t=await y(m,n);if(f=t.totalHits,u(),t.hits.length===0){a(),i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}else b(t.hits),A();Math.ceil(f/q)<=n?(a(),i.error({message:"No more pictures"})):S()}catch(t){a(),u(),h(),i.error({message:`Sorry, ${t}!`})}}_.addEventListener("click",B);async function B(){w(),n++;try{const o=await y(m,n);if(u(),o.hits.length===0)a(),h(),i.error({message:"Sorry, there are no images matching your search query. Please try again!"});else{b(o.hits);const t=document.querySelector(".gallery-item");if(t){const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}if(Math.ceil(f/q)<=n){a(),i.error({message:"We are sorry, but you have reached the end of search results"});return}else S()}catch(o){u(),a(),h(),i.error({message:`Sorry, ${o}!`})}}
//# sourceMappingURL=index.js.map
