import{a as M,S as O,i as s}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&c(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();async function g(o,t){return(await M("https://pixabay.com/api/",{params:{key:"52541066-61f39c635ccb9e2a2a197a680",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}})).data}let m;const p=document.querySelector(".loader"),L=document.querySelector(".button"),b=document.querySelector(".gallery");function w(o){const t=o.map(({webformatURL:n,largeImageURL:c,tags:e,likes:r,views:u,comments:$,downloads:P})=>`<li class="gallery-item">
  <a class="gallery-link" href="${c}">
    <img
      class="gallery-image"
      src="${n}"
      alt="${e}"
    />
  </a>
  <ul class = "discription">
  <li class = "item"><h2 class = "title">Likes</h2>${r}</li>
  <li class = "item"><h2 class = "title">Views</h2>${u}</li>
  <li class = "item"><h2 class = "title">Comments</h2>${$}</li>
  <li class = "item"><h2 class = "title">Downloads</h2>${P}</li>
  </ul>
</li>`).join("");b.insertAdjacentHTML("beforeend",t),m?m.refresh():(m=new O(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,captionPosition:"bottom"}),m.on("show.simplelightbox",function(n){console.log(`Open: ${n.target.querySelector("img").alt}`)}))}function d(){b.innerHTML=""}function S(){p.classList.remove("hidden")}function i(){p.classList.add("hidden")}function q(){L.classList.remove("hidden")}function a(){L.classList.add("hidden")}const A=document.querySelector(".form"),y=document.querySelector("input"),E=document.querySelector(".button");A.addEventListener("submit",_);let h,l=1,f=0,v=15;async function _(o){if(o.preventDefault(),l=1,S(),h=o.target.elements["search-text"].value.toLowerCase().trim(),h===""){i(),a(),s.warning({message:"Please fill in all required fields"});return}try{const t=await g(h,l);if(f=t.totalHits,i(),t.hits.length===0){d(),a(),y.value="",s.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}else d(),w(t.hits),l+=1,q(),y.value="";Math.ceil(f/v)<l&&(i(),a(),s.error({message:"No more pictures"}))}catch(t){a(),i(),d(),s.error({message:`Sorry, ${t}!`})}}E.addEventListener("click",x);async function x(){if(S(),Math.ceil(f/v)<l){i(),a(),s.error({message:"We are sorry, but you have reached the end of search results"});return}try{const o=await g(h,l);if(i(),o.hits.length===0)a(),d(),s.error({message:"Sorry, there are no images matching your search query. Please try again!"});else{q(),w(o.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),l+=1}}catch(o){i(),a(),d(),s.error({message:`Sorry, ${o}!`})}}
//# sourceMappingURL=index.js.map
